# For general information of how to configure prospector visit
# https://prospector.landscape.io/en/master/profiles.html

inherits:
  - strictness_high

pep257:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213

pylint:
  options:
    max-attributes: 12
    max-module-lines: 1800

pyroma:
  run: true
