# For general information of how to configure prospector visit
# https://prospector.landscape.io/en/master/profiles.html

inherits:
  - strictness_high

pep257:
  run: true
  disable:
    - D107
    - D203
    - D212
    - D213
    - D415
    - D416

pylint:
  options:
    max-attributes: 16
    max-module-lines: 3500

pyroma:
  run: true

bandit:
  run: true
